artifact_location: file:///C:/Users/My PC/Desktop/Flight-Data-System/ml/mlflow_tracking/0
creation_time: 1773637784681
experiment_id: '0'
last_update_time: 1773637784681
lifecycle_stage: active
name: Default
