version: 2

models:
  - name: stg_flights
    description: "Cleaned and standardized flight data from raw.flights"
    columns:
      - name: flight_number
        description: "Unique flight identifier"
        tests:
          - not_null

      - name: flight_date
        description: "Date of the flight"
        tests:
          - not_null

      - name: origin_airport
        description: "IATA code of origin airport"
        tests:
          - not_null

      - name: destination_airport
        description: "IATA code of destination airport"
        tests:
          - not_null

      - name: flight_type
        description: "domestic or international"
        tests:
          - not_null
          - accepted_values:
              values: ["domestic", "international"]

      - name: flight_status
        description: "Current status of flight"
        tests:
          - not_null
          - accepted_values:
              values: ["scheduled", "active", "landed", "cancelled", "unknown", "on_ground"]

  - name: fact_flights
    description: "Enriched flight fact table with delay categories"
    columns:
      - name: flight_number
        description: "Unique flight identifier"
        tests:
          - not_null

      - name: is_delayed
        description: "True if arrival delay more than 15 mins"
        tests:
          - not_null

      - name: delay_category
        description: "no delay, minor, moderate, severe"
        tests:
          - not_null
          - accepted_values:
              values: ["no delay", "minor", "moderate", "severe"]

      - name: time_of_day
        description: "morning, afternoon, evening, night"
        tests:
          - not_null
          - accepted_values:
              values: ["morning", "afternoon", "evening", "night"]